# Mongo field names
YEAR_CODE = 'Year Code'
AREA_CODE = 'Area Code'
AREA = 'Area'
ITEM_CODE = 'Item Code'
VALUE = 'Value'
FLAG = 'Flag'
UNIT = 'Unit'
ELEMENT_CODE = 'Element Code'

# Element codes
YIELD_ELEMENT_CODE = 5419
AREA_HARVESTED_ELEMENT_CODE = 5312
PRODUCTION_ELEMENT_CODE = 5510 # (tonnes)
PRODUCTION_EGGS_ELEMENT_CODE = 5513 # (1000 No)
AREA_ELEMENT_CODE = 5110 # (1000 ha)
STOCKS_ELEMENT_CODE = 5111
LAYING_ELEMENT_CODE = 5313
MILK_ANIMALS_ELEMENT_CODE = 5318 # (Head)
INDIGENOUS_PRODUCTION_ELEMENT_CODE = 5322 # (Head)
INDIGENOUS_PRODUCTION_1000_ELEMENT_CODE = 5323 # (1000 Head)
PRODUCING_ANIMALS_HEAD_ELEMENT_CODE = 5320 # (Head Producing/Slaughtered)
PRODUCING_ANIMALS_1000HEAD_ELEMENT_CODE = 5321 # (1000 Head Producing/Slaughtered)
LAYING_ANIMAL_YIELD_ELEMENT_CODE = 5410 # (100mg/An)
CARCASS_WEIGHT_ELEMENT_CODE = 5417 # (hg/An)
MILK_AND_SKINS_YIELD_ELEMENT_CODE = 5420 # (hg/An)
WOOL_AND_BEE_YIELD_ELEMENT_CODE = 5422 # (hg)
CARCASS_WEIGHT_SMALL_ANIMALS_ELEMENT_CODE = 5424 # (0.1g/An)
PRODUCING_WOOL_POPULATION_ELEMENT_CODE = 5319 # (Head)
PRODUCING_BEE_POPULATION_ELEMENT_CODE = 5314 # (No)

# Item codes
COUNTRY_AREA_ITEM_CODE = 6600

# Mongo collection names
PRODUCTION_CROPS_COL = 'production_crops'
PRODUCTION_LIVESTOCK_COL = 'production_livestock'
PRODUCTION_LIVESTOCK_PRIMARY_COL = 'production_livestock_primary'
LAND_USE_COL = 'inputs_land_use'